# Generated by Django 4.0.5 on 2022-06-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('ano_fabricacao', models.CharField(max_length=12)),
                ('ano_modelo', models.CharField(max_length=12)),
                ('cor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=13)),
                ('endereco', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('nome_pai', models.CharField(max_length=30)),
                ('nome_mae', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=13)),
                ('endereco', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('nome_pai', models.CharField(max_length=30)),
                ('nome_mae', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=5)),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.carro')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.cliente')),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.mecanico')),
            ],
        ),
    ]
